CREATE TABLE IF NOT EXISTS `synced_webhotelier_bookings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `member_id` BIGINT UNSIGNED NULL,
  `booking_number` VARCHAR(255) NOT NULL,
  `guest_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `check_in` DATE NULL,
  `check_out` DATE NULL,
  `rooms` INT UNSIGNED NULL,
  `room_type` VARCHAR(255) NULL,
  `room_name` VARCHAR(255) NULL,
  `rate_name` VARCHAR(255) NULL,
  `currency` VARCHAR(10) NULL,
  `booking_total` DECIMAL(14, 2) NULL,
  `status` VARCHAR(255) NULL,
  `source_name` VARCHAR(255) NULL,
  `remote_updated_at` TIMESTAMP NULL,
  `last_synced_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `synced_webhotelier_bookings_booking_number_unique` (`booking_number`),
  KEY `synced_webhotelier_bookings_member_id_check_in_index` (`member_id`, `check_in`),
  KEY `synced_webhotelier_bookings_email_index` (`email`),
  KEY `synced_webhotelier_bookings_status_index` (`status`),
  KEY `synced_webhotelier_bookings_remote_updated_at_index` (`remote_updated_at`),
  KEY `synced_webhotelier_bookings_last_synced_at_index` (`last_synced_at`),
  CONSTRAINT `synced_webhotelier_bookings_member_id_foreign`
    FOREIGN KEY (`member_id`) REFERENCES `members` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `booking_sync_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `started_at` TIMESTAMP NULL,
  `finished_at` TIMESTAMP NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'running',
  `bookings_received` INT UNSIGNED NOT NULL DEFAULT 0,
  `bookings_created` INT UNSIGNED NOT NULL DEFAULT 0,
  `bookings_updated` INT UNSIGNED NOT NULL DEFAULT 0,
  `members_created` INT UNSIGNED NOT NULL DEFAULT 0,
  `members_updated` INT UNSIGNED NOT NULL DEFAULT 0,
  `message` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `booking_sync_logs_started_at_index` (`started_at`),
  KEY `booking_sync_logs_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
