-- Voucher Products.docx catalogue import
-- MySQL / MariaDB, safe to run more than once.
-- Prices are stored as base prices with 10% service and 11% tax added at checkout.

START TRANSACTION;

INSERT INTO voucher_categories (`name`, `slug`, `description`, `is_active`, `sort_order`, `created_at`, `updated_at`)
VALUES
    ('Signature Dining Experiences', 'signature-dining-experiences', 'Memorable dining moments with scenic settings, refined flavors, and warm Balinese hospitality.', 1, 10, NOW(), NOW()),
    ('Jungle Romance', 'jungle-romance', 'Intimate moments crafted for couples, surrounded by the beauty of Ubud''s jungle and river.', 1, 20, NOW(), NOW()),
    ('Jungle Wellness & Spa Rituals', 'jungle-wellness-spa-rituals', 'Relaxing rituals designed to restore balance, refresh the body, and calm the mind.', 1, 30, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    `name` = VALUES(`name`),
    `description` = VALUES(`description`),
    `is_active` = VALUES(`is_active`),
    `sort_order` = VALUES(`sort_order`),
    `updated_at` = NOW();

SET @dining_category = (SELECT `id` FROM `voucher_categories` WHERE `slug` = 'signature-dining-experiences' LIMIT 1);
SET @romance_category = (SELECT `id` FROM `voucher_categories` WHERE `slug` = 'jungle-romance' LIMIT 1);
SET @wellness_category = (SELECT `id` FROM `voucher_categories` WHERE `slug` = 'jungle-wellness-spa-rituals' LIMIT 1);
SET @voucher_terms = '<h3>Usage Terms</h3><ul><li>The voucher is valid for 12 months from the date of purchase.</li><li>Advance reservation is required. To redeem your voucher, please contact our Reservations Team via email at reservation@nandinibali.com or WhatsApp at +62 812 3687 1170.</li><li>The voucher is non-refundable, non-transferable, and cannot be exchanged for cash, either in whole or in part.</li><li>The voucher cannot be used in conjunction with any other promotions, discounts, special offers, or packages unless otherwise stated.</li><li>Blackout dates may apply.</li></ul><h3>Payment Terms</h3><ul><li>Please note that all payments are non-refundable once successfully completed.</li></ul>';

INSERT INTO `vouchers`
    (`voucher_category_id`, `title`, `slug`, `sku`, `excerpt`, `description`, `terms_conditions`, `voucher_type`, `face_value`, `selling_price`, `currency`, `price_type`, `unit_type`, `validity_type`, `validity_days`, `minimum_quantity`, `purchase_limit_per_order`, `allow_partial_redemption`, `is_active`, `sort_order`, `created_at`, `updated_at`)
VALUES
(@dining_category, 'The Floating Boat Experience', 'the-floating-boat-experience', 'EXP-THEFLOATINGBOATEXPERIENCE', 'Start your morning with an iconic Floating Breakfast for two in the pool overlooking the jungle.', '<p>Start your morning with one of our most iconic experiences—a Floating Breakfast for two, served in the pool overlooking the breathtaking jungle panorama. Beautifully presented and perfect for capturing unforgettable moments, this unique breakfast experience combines indulgence with the tranquility of nature.</p><p>To ensure maximum privacy and comfort, your breakfast is served early in the morning before the pool opens for daily operations.</p>', @voucher_terms, 'dining', 3267000, 3267000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 1, NOW(), NOW()),
(@dining_category, 'Luxe High Tea', 'luxe-high-tea', 'EXP-LUXEHIGHTEA', 'Savor an elegant afternoon with our Luxe High Tea, set against the serene beauty of Ubud''s lush jungle.', '<p>Savor an elegant afternoon with our Luxe High Tea, set against the serene beauty of Ubud''s lush jungle. Indulge in a curated selection of premium teas or freshly brewed coffee, accompanied by an exquisite assortment of handcrafted sweet and savory delicacies inspired by both Eastern and Western flavors.</p><p>Perfectly designed for two, this sophisticated experience invites you to slow down, connect, and embrace the tranquil ambiance as the afternoon gently unfolds into a peaceful evening.</p>', @voucher_terms, 'dining', 907500, 907500, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 2, NOW(), NOW()),
(@dining_category, 'Cooking Class', 'cooking-class', 'EXP-COOKINGCLASS', 'Discover the rich flavors and traditions of Balinese cuisine with our immersive Cooking Class.', '<p>Discover the rich flavors and traditions of Balinese cuisine with our immersive Cooking Class, led by Executive Chef Gustu. Passionate about sharing the island''s culinary heritage, Chef Gustu invites you to experience the art of authentic Balinese cooking through a hands-on and enjoyable journey.</p>', @voucher_terms, 'dining', 4235000, 4235000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 3, NOW(), NOW()),
(@dining_category, 'Moonlit Jungle Romance', 'moonlit-jungle-romance', 'EXP-MOONLITJUNGLEROMANCE', 'An intimate candlelight dinner by Nandini''s jungle pool.', '<p>An Intimate Candlelight Dinner by Nandini''s Jungle Pool. Celebrate love with an unforgettable evening beneath the stars, surrounded by the enchanting beauty of Bali''s lush jungle. Set beside Nandini''s tranquil infinity pool, this exclusive dining experience features a beautifully crafted four-course dinner, thoughtfully prepared by our culinary team.</p>', @voucher_terms, 'dining', 10285000, 10285000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 4, NOW(), NOW()),
(@dining_category, 'Riverside Romance', 'riverside-romance', 'EXP-RIVERSIDEROMANCE', 'An intimate candlelight dinner by the mystical Ayung River.', '<p>An Intimate Candlelight Dinner by the Mystical Ayung River. Experience an unforgettable evening on a secluded wooden deck overlooking the mystical Ayung River. Surrounded by lush jungle and the warm glow of hundreds of candles, indulge in a romantic six-course dinner while the soothing sound of the flowing river creates a truly magical atmosphere.</p>', @voucher_terms, 'dining', 16002250, 16002250, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 5, NOW(), NOW()),
(@dining_category, 'Romantic Dining by The Chapel', 'romantic-dining-by-the-chapel', 'EXP-ROMANTICDININGBYTHECHAPEL', 'Celebrate love with an intimate candlelight dinner beside our iconic chapel.', '<p>Celebrate love with an intimate candlelight dinner beside our iconic chapel, overlooking the enchanting jungle and tranquil pool. Savor a specially curated dinner under the stars, where breathtaking views and a romantic ambiance create an unforgettable evening for two.</p>', @voucher_terms, 'dining', 7865000, 7865000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 6, NOW(), NOW()),
(@dining_category, 'A 2-Course Set Lunch for Two', 'a-2-course-set-lunch-for-two', 'EXP-2COURSESETLUNCHFORTWO', 'Enjoy a thoughtfully curated 2-course set lunch for two.', '<p>Enjoy a delightful dining experience for two with a thoughtfully curated 2-course set menu. Personalize your meal by choosing either a starter and main course or a main course and dessert, with a selection of dishes crafted from fresh, locally inspired ingredients. Whether you''re sharing a leisurely afternoon or celebrating a special occasion, this dining experience offers the perfect balance of flavor and indulgence in a tranquil jungle setting.</p>', @voucher_terms, 'dining', 800000, 800000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 7, NOW(), NOW()),
(@dining_category, 'A 2-Course Set Dinner for Two', 'a-2-course-set-dinner-for-two', 'EXP-2COURSESETDINNERFORTWO', 'Savor an intimate 2-course set dinner for two.', '<p>Savor an intimate dining experience for two with a thoughtfully curated 2-course set dinner. Create your perfect meal by choosing either a starter and main course or a main course and dessert, featuring a selection of dishes crafted from fresh, locally inspired ingredients. Whether you''re celebrating a special occasion or simply enjoying a romantic evening together, this dining experience offers the perfect blend of exquisite flavors and warm hospitality in the enchanting ambiance of the jungle.</p>', @voucher_terms, 'dining', 1200000, 1200000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 8, NOW(), NOW()),
(@dining_category, 'Signature Nasi Jinggo', 'signature-nasi-jinggo', 'EXP-SIGNATURENASIJINGGO', 'Experience Bali''s iconic Nasi Jinggo, reimagined by Chef Gustu for two persons.', '<p>Designed for 2 persons, experience Bali''s iconic Nasi Jinggo, reimagined by Chef Gustu into a refined dining journey. Delight in fragrant banana leaf-wrapped rice accompanied by sambal lobster, honey-grilled chicken, beef and calamari satays, Balinese pickles, and aromatic Pepes Ikan Kemangi. Thoughtfully crafted with premium ingredients, this signature dining experience celebrates the authentic flavors of Bali in the enchanting setting of Nandini Jungle by Hanging Gardens.</p>', @voucher_terms, 'dining', 2200000, 2200000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 9, NOW(), NOW()),
(@dining_category, 'One Hour Free Flow Cocktails for One Person', 'one-hour-free-flow-cocktails-for-one-person', 'EXP-FREEFLOWCOCKTAILS1', 'Unwind by the pool with one hour of free-flow signature cocktails and light snacks.', '<p>Unwind by the pool with one hour of free-flow signature cocktails from 1:00 PM to 2:00 PM, accompanied by a selection of light snacks. Sit back, sip, and soak in the tranquil jungle ambiance for the perfect afternoon escape.</p>', @voucher_terms, 'dining', 800000, 800000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 10, NOW(), NOW()),
(@dining_category, 'One Hour Free Flow Cocktails for Two Persons', 'one-hour-free-flow-cocktails-for-two-persons', 'EXP-FREEFLOWCOCKTAILS2', 'Enjoy one hour of free-flow signature cocktails for two with light snacks.', '<p>Treat yourself and your companion to one hour of free-flow signature cocktails for two persons from 1:00 PM to 2:00 PM, complemented by a selection of light snacks. Relax by the pool, savor handcrafted cocktails, and enjoy the serene jungle atmosphere for the perfect afternoon escape together.</p>', @voucher_terms, 'dining', 1200000, 1200000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 11, NOW(), NOW()),
(@dining_category, 'One Hour Free Flow Mixed Cocktails & Beer for One Person', 'one-hour-free-flow-mixed-cocktails-beer-for-one-person', 'EXP-FREEFLOWMIXED1', 'Enjoy one hour of free-flow mixed cocktails and beer with light snacks.', '<p>Enjoy one hour of free-flow mixed cocktails and beer for one person, served from 1:00 PM to 2:00 PM, accompanied by a selection of light snacks. Relax by the pool, sip your favorite drinks, and immerse yourself in the tranquil ambiance of Nandini Jungle by Hanging Gardens for a refreshing afternoon escape.</p>', @voucher_terms, 'dining', 900000, 900000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 12, NOW(), NOW()),
(@dining_category, 'One Hour Free Flow Mixed Cocktails & Beer for Two Persons', 'one-hour-free-flow-mixed-cocktails-beer-for-two-persons', 'EXP-FREEFLOWMIXED2', 'Share one hour of free-flow mixed cocktails and beer for two with light snacks.', '<p>Share a relaxing afternoon with one hour of free-flow mixed cocktails and beer for two persons, served from 1:00 PM to 2:00 PM, accompanied by a selection of light snacks. Unwind by the pool, enjoy handcrafted drinks, and soak in the peaceful jungle ambiance of Nandini Jungle by Hanging Gardens together.</p>', @voucher_terms, 'dining', 1400000, 1400000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 13, NOW(), NOW()),
(@dining_category, 'One Hour Free Flow Wine for One Person', 'one-hour-free-flow-wine-for-one-person', 'EXP-FREEFLOWWINE1', 'Indulge in one hour of free-flow wine with light snacks.', '<p>Indulge in one hour of free-flow wine for one person, served from 1:00 PM to 2:00 PM, featuring your choice of Two Islands Selection or Louis Perdrier Sparkling Wine. Complemented by a selection of light snacks, this relaxing experience is the perfect way to unwind by the pool while enjoying the tranquil jungle ambiance of Nandini Jungle by Hanging Gardens.</p>', @voucher_terms, 'dining', 1000000, 1000000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 14, NOW(), NOW()),
(@dining_category, 'One Hour Free Flow Wine for Two Persons', 'one-hour-free-flow-wine-for-two-persons', 'EXP-FREEFLOWWINE2', 'Enjoy one hour of free-flow wine for two with light snacks.', '<p>Enjoy one hour of free-flow wine for two persons, served from 1:00 PM to 2:00 PM, featuring a selection of Two Islands wines or Louis Perdrier Sparkling Wine. Complemented by a selection of light snacks, this shared experience is perfect for relaxing by the pool while soaking in the tranquil jungle ambiance of Nandini Jungle by Hanging Gardens.</p>', @voucher_terms, 'dining', 1600000, 1600000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 15, NOW(), NOW()),
(@romance_category, 'Welcome Champagne in the Room', 'welcome-champagne-in-the-room', 'EXP-WELCOMECHAMPAGNE', 'A bottle of Zonin Prosecco DOC, Italy, prepared in your room upon arrival.', '<p>Celebrate life''s most memorable moments with a bottle of Zonin Prosecco DOC, Italy, thoughtfully prepared in your room upon arrival. Whether you''re celebrating your honeymoon, anniversary, or another special occasion, this elegant welcome sets the perfect tone for a romantic stay at Nandini Jungle by Hanging Gardens.</p>', @voucher_terms, 'dining', 2200000, 2200000, 'IDR', 'plus_plus', 'per_booking', 'days_after_issue', 365, 1, 10, 0, 1, 16, NOW(), NOW()),
(@romance_category, 'A Sparkling Welcome', 'a-sparkling-welcome', 'EXP-ASPARKLINGWELCOME', 'A bottle of Balinese sparkling wine prepared in your room upon arrival.', '<p>Celebrate your special moments with a bottle of Balinese sparkling wine, thoughtfully prepared in your room upon arrival. Choose between Tunjung Sparkling Brut or Jepun Sparkling Rosé, both crafted in Bali to add a local touch to your celebration. Whether you''re celebrating your honeymoon, anniversary, birthday, or simply creating unforgettable memories, this elegant welcome sets the perfect tone for a romantic stay at Nandini Jungle by Hanging Gardens.</p>', @voucher_terms, 'dining', 1150000, 1150000, 'IDR', 'plus_plus', 'per_booking', 'days_after_issue', 365, 1, 10, 0, 1, 17, NOW(), NOW()),
(@romance_category, 'Flower Decoration', 'flower-decoration', 'EXP-FLOWERDECORATION', 'Create an unforgettable room decoration surprise for your loved one.', '<p>Create unforgettable moments in the heart of the jungle with our special room decoration surprise, thoughtfully designed for your loved one. Whether you are celebrating a birthday, anniversary, honeymoon, or any romantic occasion, let us transform your stay into a memorable experience with beautifully decorated arrangements and heartfelt touches.</p>', @voucher_terms, 'experience', 1850000, 1850000, 'IDR', 'plus_plus', 'per_booking', 'days_after_issue', 365, 1, 10, 0, 1, 18, NOW(), NOW()),
(@wellness_category, 'Rejuvenating Cem Ceman Therapy', 'rejuvenating-cem-ceman-therapy', 'EXP-REJUVENATINGCEMCEMAN', 'A 90-minute Balinese massage and traditional Cem-Ceman hair treatment for one person.', '<p>Indulge in a 90-minute wellness experience for one person, featuring a relaxing Traditional Balinese Massage followed by a soothing hair treatment and scalp massage using traditional Cem-Ceman herbal oil. This nourishing ritual helps relieve tension while leaving your hair soft, silky, and beautifully revitalized.</p>', @voucher_terms, 'spa', 2265120, 2265120, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 19, NOW(), NOW()),
(@wellness_category, 'Exotic Balinese Massage', 'exotic-balinese-massage', 'EXP-EXOTICBALINESEMASSAGE', 'A 60-minute Traditional Balinese Massage for one person.', '<p>Experience a 60-minute Traditional Balinese Massage for one person, featuring gentle rolling, deep kneading, and acupressure techniques using nourishing organic coconut oil. This time-honored healing ritual helps improve blood circulation, ease muscle tension, and restore harmony to your body and mind, leaving you feeling deeply relaxed, refreshed, and revitalized.</p>', @voucher_terms, 'spa', 1597200, 1597200, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 20, NOW(), NOW()),
(@wellness_category, 'Bliss Massage', 'bliss-massage', 'EXP-BLISSMASSAGE', 'A 60-minute firm-pressure massage for one person targeting chronic muscle tension.', '<p>Experience a 60-minute Bliss Massage for one person, employing firm pressure and slow, deliberate strokes to target chronic muscle tension and release tightness deeply embedded within the muscles and connective tissues. This therapeutic treatment helps improve mobility, relieve stress, reduce muscle stiffness, and restore your body to a state of deep relaxation and renewed vitality.</p>', @voucher_terms, 'spa', 2003760, 2003760, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 21, NOW(), NOW()),
(@wellness_category, 'Signature Spa on the River', 'nandini-signature-spa-on-the-river', 'EXP-NANDINISIGNATURESPAONTHERIVER', 'A three-hour signature wellness journey for one person by the Ayung River.', '<p>Experience our signature spa ritual by the tranquil Ayung River, where the soothing sounds of nature create the perfect setting for complete relaxation. This 3-hour wellness journey for one person begins with our signature Holy Exotic Balinese Massage, followed by a Traditional Balinese Body Scrub &amp; Body Mask to gently exfoliate and nourish the skin. Complete your experience with a Relaxing Facial Treatment, leaving your skin refreshed, radiant, and beautifully revitalized. An immersive spa escape inspired by Bali''s ancient healing traditions, designed to restore harmony to your body, mind, and spirit.</p>', @voucher_terms, 'spa', 5324000, 5324000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 22, NOW(), NOW()),
(@wellness_category, 'Riverside Sanctuary Spa Package', 'riverside-sanctuary-spa-package', 'EXP-RIVERSIDESANCTUARYSPAPACKAGE', 'A two-hour riverside spa experience for one person.', '<p>Enjoy a 2-hour spa experience for one person by the serene riverside, surrounded by the calming sounds of nature. Begin with our signature Exotic Balinese Massage to ease tension and restore balance, followed by a Traditional Balinese Body Scrub &amp; Body Mask to gently exfoliate, nourish, and leave your skin feeling smooth, refreshed, and naturally radiant. A rejuvenating wellness ritual inspired by Bali''s timeless healing traditions.</p>', @voucher_terms, 'spa', 4660920, 4660920, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 23, NOW(), NOW()),
(@wellness_category, 'Luxury Wine Spa Package', 'luxury-spa-package-wine-spa', 'EXP-LUXURYSPAPACKAGEWINESPA', 'A 2.5-hour wine-inspired spa experience for one person.', '<p>Treat yourself to a 2.5-hour spa experience for one person, designed to relax the body and indulge the senses. Begin with a soothing Traditional Balinese Massage, followed by a rejuvenating Wine Body Scrub &amp; Body Mask to gently exfoliate and nourish the skin. Continue your journey with a luxurious Wine Bath, rich in natural antioxidants that help soften and revitalize the skin, while enjoying a complimentary glass of red wine. The perfect spa ritual for those seeking relaxation, rejuvenation, and a touch of indulgence.</p>', @voucher_terms, 'spa', 5324000, 5324000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 24, NOW(), NOW()),
(@wellness_category, 'Riverside Picnic and Wellness Retreat', 'riverside-bliss-half-day-picnic-and-wellness-escape-at-the-river', 'EXP-RIVERSIDEBLISSHALFDAYPICNICANDWELLNESSESCAPEATTHERIVER', 'A romantic riverside picnic and two-hour Balinese massage for two.', '<p>Escape into the heart of Ubud''s lush jungle with a romantic riverside experience for two, thoughtfully designed for relaxation and connection. Begin with an intimate picnic by the scenic river''s edge, where you can savor delicious refreshments while surrounded by the tranquil sounds of flowing water and tropical nature.</p><p>Continue your journey with a 2-hour Traditional Balinese Massage for two in our serene spa room. Performed by skilled therapists, this restorative treatment uses time-honored Balinese techniques to ease muscle tension, improve circulation, and restore harmony to the body and mind.</p>', @voucher_terms, 'spa', 6655000, 6655000, 'IDR', 'plus_plus', 'per_couple', 'days_after_issue', 365, 1, 10, 0, 1, 25, NOW(), NOW()),
(@wellness_category, 'Yoga Meditation at Sacred River', 'yoga-or-chakra-meditation-at-sacred-river', 'EXP-YOGAORCHAKRAMEDITATIONATSACREDRIVER', 'A private riverside yoga or chakra meditation session for one person.', '<p>Reconnect with your inner self through a private riverside yoga or chakra meditation session for one person. Surrounded by the soothing sounds of the sacred river and lush jungle, this restorative experience helps restore balance, enhance mindfulness, and cultivate deep inner peace in harmony with the natural beauty of Bali.</p>', @voucher_terms, 'spa', 2178000, 2178000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 26, NOW(), NOW()),
(@wellness_category, 'A Sacred Moment of Renewal', 'a-sacred-moment-of-renewal', 'EXP-ASACREDMOMENTOFRENEWAL', 'A 75-minute guided purification and meditation ritual for one person.', '<p>Experience a 75-minute guided wellness ritual for one person, rooted in Balinese tradition and surrounded by the serenity of the jungle. Begin with a 30-minute Blessing Purification Ceremony, followed by a 45-minute riverside meditation designed to restore balance, calm the mind, and renew your body, spirit, and inner peace.</p>', @voucher_terms, 'experience', 3025000, 3025000, 'IDR', 'plus_plus', 'per_person', 'days_after_issue', 365, 1, 10, 0, 1, 27, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    `voucher_category_id` = VALUES(`voucher_category_id`),
    `title` = VALUES(`title`),
    `sku` = VALUES(`sku`),
    `excerpt` = VALUES(`excerpt`),
    `description` = VALUES(`description`),
    `terms_conditions` = VALUES(`terms_conditions`),
    `voucher_type` = VALUES(`voucher_type`),
    `face_value` = VALUES(`face_value`),
    `selling_price` = VALUES(`selling_price`),
    `currency` = VALUES(`currency`),
    `price_type` = VALUES(`price_type`),
    `unit_type` = VALUES(`unit_type`),
    `validity_type` = VALUES(`validity_type`),
    `validity_days` = VALUES(`validity_days`),
    `minimum_quantity` = VALUES(`minimum_quantity`),
    `purchase_limit_per_order` = VALUES(`purchase_limit_per_order`),
    `allow_partial_redemption` = VALUES(`allow_partial_redemption`),
    `is_active` = VALUES(`is_active`),
    `sort_order` = VALUES(`sort_order`),
    `deleted_at` = NULL,
    `updated_at` = NOW();

COMMIT;

