<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SpaSetting extends Model
{
    protected $fillable = [
        'reservation_whatsapp',
        'reservation_url',
        'meta_title',
        'meta_description',
        'meta_author',
        'meta_site_name',
        'hero_visible',
        'hero_image',
        'hero_mobile_image',
        'hero_image_alt',
        'hero_mobile_image_alt',
        'hero_eyebrow',
        'hero_heading',
        'hero_subheading',
        'hero_description',
        'hero_primary_cta_label',
        'hero_primary_cta_url',
        'hero_secondary_cta_label',
        'hero_secondary_cta_url',
        'information_bar_visible',
        'information_bar_items',
        'wellness_philosophy_visible',
        'wellness_philosophy_eyebrow',
        'wellness_philosophy_heading',
        'wellness_philosophy_description',
        'wellness_philosophy_image',
        'wellness_philosophy_image_alt',
        'wellness_philosophy_link_label',
        'wellness_philosophy_link_url',
        'why_nandini_visible',
        'why_nandini_eyebrow',
        'why_nandini_heading',
        'why_nandini_items',
        'wellness_journeys_visible',
        'wellness_journeys_eyebrow',
        'wellness_journeys_heading',
        'wellness_journeys_description',
        'wellness_journeys_items',
        'signature_visible',
        'signature_eyebrow',
        'signature_heading',
        'signature_description',
        'signature_image',
        'signature_image_alt',
        'signature_link_label',
        'signature_link_url',
        'guest_review_visible',
        'guest_review_quote',
        'guest_review_label',
        'guest_review_image',
        'guest_review_image_alt',
        'booking_cta_visible',
        'booking_cta_eyebrow',
        'booking_cta_heading',
        'booking_cta_description',
        'booking_cta_button_label',
        'booking_cta_button_url',
        'booking_cta_image',
        'booking_cta_image_alt',
    ];

    protected $casts = [
        'hero_visible' => 'boolean',
        'information_bar_visible' => 'boolean',
        'wellness_philosophy_visible' => 'boolean',
        'why_nandini_visible' => 'boolean',
        'wellness_journeys_visible' => 'boolean',
        'signature_visible' => 'boolean',
        'guest_review_visible' => 'boolean',
        'booking_cta_visible' => 'boolean',
        'information_bar_items' => 'array',
        'why_nandini_items' => 'array',
        'wellness_journeys_items' => 'array',
    ];
}
